[2024-11-11T18:47:40.864+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-11T18:47:40.875+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: modeling_pipeline.Random_Forest_model manual__2024-11-11T18:46:32.526075+00:00 [queued]>
[2024-11-11T18:47:40.878+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: modeling_pipeline.Random_Forest_model manual__2024-11-11T18:46:32.526075+00:00 [queued]>
[2024-11-11T18:47:40.878+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-11T18:47:40.883+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): Random_Forest_model> on 2024-11-11 18:46:32.526075+00:00
[2024-11-11T18:47:40.892+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=204) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-11T18:47:40.892+0000] {standard_task_runner.py:63} INFO - Started process 213 to run task
[2024-11-11T18:47:40.893+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'modeling_pipeline', 'Random_Forest_model', 'manual__2024-11-11T18:46:32.526075+00:00', '--job-id', '927', '--raw', '--subdir', 'DAGS_FOLDER/dag_script_model.py', '--cfg-path', '/tmp/tmp79lwk9e4']
[2024-11-11T18:47:40.895+0000] {standard_task_runner.py:91} INFO - Job 927: Subtask Random_Forest_model
[2024-11-11T18:47:40.915+0000] {task_command.py:426} INFO - Running <TaskInstance: modeling_pipeline.Random_Forest_model manual__2024-11-11T18:46:32.526075+00:00 [running]> on host 5039cd089413
[2024-11-11T18:47:40.950+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='MLOPS' AIRFLOW_CTX_DAG_ID='modeling_pipeline' AIRFLOW_CTX_TASK_ID='Random_Forest_model' AIRFLOW_CTX_EXECUTION_DATE='2024-11-11T18:46:32.526075+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-11T18:46:32.526075+00:00'
[2024-11-11T18:47:40.951+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-11T18:47:40.969+0000] {logging_mixin.py:188} INFO - Data loaded from /opt/***/dags/DataPreprocessing/src/data_store_pkl_files/test_data/no_anamoly_test_data.pkl.
[2024-11-11T18:47:40.970+0000] {logging_mixin.py:188} INFO - Original Skewness: 0.5082849280995185
[2024-11-11T18:47:40.971+0000] {logging_mixin.py:188} INFO - Log Transformed Skewness: -0.38788987353405835
[2024-11-11T18:47:40.980+0000] {logging_mixin.py:188} INFO - Box-Cox Transformed Skewness: 0.011851083745351043
[2024-11-11T18:47:40.980+0000] {logging_mixin.py:188} INFO - Choosing Box-Cox transformed column.
[2024-11-11T18:47:40.987+0000] {logging_mixin.py:188} INFO - Feature engineering completed and NaN values dropped.
[2024-11-11T18:47:41.010+0000] {logging_mixin.py:188} WARNING - 2024/11/11 18:47:41 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2024-11-11T18:47:51.863+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/mlflow/types/utils.py:407: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details.
  warnings.warn(

[2024-11-11T18:47:54.276+0000] {logging_mixin.py:188} WARNING - Downloading artifacts:   0%|          | 0/7 [00:00<?, ?it/s]
[2024-11-11T18:47:54.277+0000] {logging_mixin.py:188} WARNING - Downloading artifacts:  14%|#4        | 1/7 [00:00<00:00, 5932.54it/s]
[2024-11-11T18:47:54.277+0000] {logging_mixin.py:188} WARNING - Downloading artifacts:  29%|##8       | 2/7 [00:00<00:00, 4288.65it/s]
[2024-11-11T18:47:54.278+0000] {logging_mixin.py:188} WARNING - Downloading artifacts:  43%|####2     | 3/7 [00:00<00:00, 4312.17it/s]
[2024-11-11T18:47:54.278+0000] {logging_mixin.py:188} WARNING - Downloading artifacts:  57%|#####7    | 4/7 [00:00<00:00, 4707.41it/s]
[2024-11-11T18:47:54.278+0000] {logging_mixin.py:188} WARNING - Downloading artifacts:  71%|#######1  | 5/7 [00:00<00:00, 4758.68it/s]
[2024-11-11T18:47:54.278+0000] {logging_mixin.py:188} WARNING - Downloading artifacts:  86%|########5 | 6/7 [00:00<00:00, 5069.67it/s]
[2024-11-11T18:47:54.278+0000] {logging_mixin.py:188} WARNING - Downloading artifacts: 100%|##########| 7/7 [00:00<00:00, 5236.33it/s]
[2024-11-11T18:47:54.278+0000] {logging_mixin.py:188} WARNING - Downloading artifacts: 100%|##########| 7/7 [00:00<00:00, 4657.38it/s]
[2024-11-11T18:47:54.359+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

[2024-11-11T18:47:54.360+0000] {logging_mixin.py:188} INFO - RMSE (Box-Cox transformed target): 0.003679692702632717
[2024-11-11T18:47:54.361+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

[2024-11-11T18:47:54.362+0000] {logging_mixin.py:188} INFO - RMSE (Original PM2.5 target): 1.0012990872806014
[2024-11-11T18:47:54.407+0000] {logging_mixin.py:188} INFO - Model saved at /opt/***/dags/weights/randomforest_pm25_model.pth
[2024-11-11T18:47:54.416+0000] {logging_mixin.py:188} INFO - Model loaded from /opt/***/dags/weights/randomforest_pm25_model.pth
[2024-11-11T18:47:54.613+0000] {logging_mixin.py:188} INFO - Plot saved at /opt/***/dags/artifacts/pm25_actual_vs_predicted_RandomForest.png
[2024-11-11T18:47:54.615+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-11-11T18:47:54.616+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-11T18:47:54.630+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=modeling_pipeline, task_id=Random_Forest_model, run_id=manual__2024-11-11T18:46:32.526075+00:00, execution_date=20241111T184632, start_date=20241111T184740, end_date=20241111T184754
[2024-11-11T18:47:54.693+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-11-11T18:47:54.715+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-11-11T18:47:54.716+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
