[2024-11-03T02:37:48.925+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-03T02:37:49.064+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: datapipeline_new.send_anomaly_alert_handle_missing_vals_train manual__2024-11-03T02:36:44.429080+00:00 [queued]>
[2024-11-03T02:37:49.069+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: datapipeline_new.send_anomaly_alert_handle_missing_vals_train manual__2024-11-03T02:36:44.429080+00:00 [queued]>
[2024-11-03T02:37:49.069+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-03T02:37:49.074+0000] {taskinstance.py:2330} INFO - Executing <Task(EmailOperator): send_anomaly_alert_handle_missing_vals_train> on 2024-11-03 02:36:44.429080+00:00
[2024-11-03T02:37:49.078+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=251) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-03T02:37:49.079+0000] {standard_task_runner.py:63} INFO - Started process 260 to run task
[2024-11-03T02:37:49.080+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'datapipeline_new', 'send_anomaly_alert_handle_missing_vals_train', 'manual__2024-11-03T02:36:44.429080+00:00', '--job-id', '721', '--raw', '--subdir', 'DAGS_FOLDER/dag_script.py', '--cfg-path', '/tmp/tmpjm2jba8t']
[2024-11-03T02:37:49.081+0000] {standard_task_runner.py:91} INFO - Job 721: Subtask send_anomaly_alert_handle_missing_vals_train
[2024-11-03T02:37:49.099+0000] {task_command.py:426} INFO - Running <TaskInstance: datapipeline_new.send_anomaly_alert_handle_missing_vals_train manual__2024-11-03T02:36:44.429080+00:00 [running]> on host 7ffb0854de89
[2024-11-03T02:37:49.134+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='MLOPS' AIRFLOW_CTX_DAG_ID='datapipeline_new' AIRFLOW_CTX_TASK_ID='send_anomaly_alert_handle_missing_vals_train' AIRFLOW_CTX_EXECUTION_DATE='2024-11-03T02:36:44.429080+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-03T02:36:44.429080+00:00'
[2024-11-03T02:37:49.134+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-03T02:37:49.143+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/email.py:154: RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2024-11-03T02:37:49.143+0000] {email.py:271} INFO - Email alerting: attempt 1
[2024-11-03T02:37:49.631+0000] {email.py:282} INFO - Sent an alert email to ['anirudhak881@gmail.com']
[2024-11-03T02:37:51.897+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-03T02:37:51.925+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=datapipeline_new, task_id=send_anomaly_alert_handle_missing_vals_train, run_id=manual__2024-11-03T02:36:44.429080+00:00, execution_date=20241103T023644, start_date=20241103T023749, end_date=20241103T023751
[2024-11-03T02:37:51.988+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-11-03T02:37:52.027+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-03T02:37:52.029+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
