[2024-11-04T05:06:57.308+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-04T05:06:57.318+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: datapipeline_new.data_remove_cols_train manual__2024-11-04T05:06:12.986905+00:00 [queued]>
[2024-11-04T05:06:57.321+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: datapipeline_new.data_remove_cols_train manual__2024-11-04T05:06:12.986905+00:00 [queued]>
[2024-11-04T05:06:57.321+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-04T05:06:57.393+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): data_remove_cols_train> on 2024-11-04 05:06:12.986905+00:00
[2024-11-04T05:06:57.398+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=193) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-04T05:06:57.399+0000] {standard_task_runner.py:63} INFO - Started process 202 to run task
[2024-11-04T05:06:57.399+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'datapipeline_new', 'data_remove_cols_train', 'manual__2024-11-04T05:06:12.986905+00:00', '--job-id', '752', '--raw', '--subdir', 'DAGS_FOLDER/dag_script.py', '--cfg-path', '/tmp/tmpyqutmkcm']
[2024-11-04T05:06:57.401+0000] {standard_task_runner.py:91} INFO - Job 752: Subtask data_remove_cols_train
[2024-11-04T05:06:57.420+0000] {task_command.py:426} INFO - Running <TaskInstance: datapipeline_new.data_remove_cols_train manual__2024-11-04T05:06:12.986905+00:00 [running]> on host 7ffb0854de89
[2024-11-04T05:06:57.453+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='MLOPS' AIRFLOW_CTX_DAG_ID='datapipeline_new' AIRFLOW_CTX_TASK_ID='data_remove_cols_train' AIRFLOW_CTX_EXECUTION_DATE='2024-11-04T05:06:12.986905+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-04T05:06:12.986905+00:00'
[2024-11-04T05:06:57.454+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-04T05:06:57.462+0000] {removal_of_uneccesary_cols.py:20} INFO - Data loaded from /opt/***/dags/DataPreprocessing/src/data_store_pkl_files/train_data/pivoted_train_data.pkl.
[2024-11-04T05:06:57.462+0000] {removal_of_uneccesary_cols.py:36} WARNING - None of the specified columns ['co', 'no', 'no2', 'o3', 'so2'] exist in the DataFrame.
[2024-11-04T05:06:57.464+0000] {removal_of_uneccesary_cols.py:64} INFO - Set 'date' column as index successfully.
[2024-11-04T05:06:57.464+0000] {removal_of_uneccesary_cols.py:99} ERROR - Anomalies detected; skipping saving the cleaned data.
[2024-11-04T05:06:57.464+0000] {python.py:237} INFO - Done. Returned value was: ["None of the columns ['co', 'no', 'no2', 'o3', 'so2'] exist in the DataFrame"]
[2024-11-04T05:06:57.464+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-04T05:06:57.471+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=datapipeline_new, task_id=data_remove_cols_train, run_id=manual__2024-11-04T05:06:12.986905+00:00, execution_date=20241104T050612, start_date=20241104T050657, end_date=20241104T050657
[2024-11-04T05:06:57.500+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-11-04T05:06:57.505+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
